from __future__ import annotations

import hashlib
import json
from pathlib import Path
import tomllib

from .layout import MachineGeometry, plan_machine
from .model import BuildPlan, Vec3
from .redstone import lamp_panel
from .worldio import AmuletWorldWriter


def load_config(path: str | Path) -> dict:
    return tomllib.loads(Path(path).read_text(encoding="utf-8"))


def build_plan(config: dict) -> BuildPlan:
    w = config["world"]
    m = config["memory"]
    d = config["display"]

    geometry = MachineGeometry(
        origin=Vec3(w["origin_x"], w["origin_y"], w["origin_z"]),
        ram_bytes=m["logical_ram_bytes"],
        cache_bytes=m["cache_bytes"],
        flash_bytes=m["flash_bytes"],
        display_width=d["width"],
        display_height=d["height"],
    )
    plan = plan_machine(geometry)

    # The display plane is already a complete physical block surface. Detailed
    # tile drivers and compute components are generated by their component
    # backends as those backends reach release-complete status.
    display = next(c for c in plan.components if c.name == "display")
    display.placements.extend(
        lamp_panel(
            display.box.min,
            d["width"],
            d["height"],
            component="display",
        )
    )
    return plan


def manifest(config: dict, plan: BuildPlan) -> dict:
    normalized = json.dumps(config, sort_keys=True, separators=(",", ":")).encode()
    result = plan.manifest()
    result.update({
        "config_sha256": hashlib.sha256(normalized).hexdigest(),
        "minecraft_version": config["world"]["minecraft_version"],
        "data_version": config["world"]["data_version"],
        "logical_ram_bytes": config["memory"]["logical_ram_bytes"],
        "cache_bytes": config["memory"]["cache_bytes"],
        "flash_bytes": config["memory"]["flash_bytes"],
        "vram_bytes": config["memory"]["vram_bytes"],
        "display": {
            "width": config["display"]["width"],
            "height": config["display"]["height"],
            "bits_per_pixel": config["display"]["bits_per_pixel"],
        },
        "physical_generation_status": "foundation",
    })
    return result


def write_manifest(path: str | Path, data: dict) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_available_placements(world_path: str | Path, config: dict, plan: BuildPlan) -> int:
    """Write placements implemented by the current physical component library.

    This function intentionally does not claim unimplemented CPU/RAM/GPU
    circuitry is complete. The manifest identifies the current physical status.
    """
    placements = plan.placements()
    if not placements:
        return 0
    with AmuletWorldWriter(
        world_path,
        dimension=config["world"]["dimension"],
        version=("java", tuple(int(x) for x in config["world"]["minecraft_version"].split("."))),
    ) as writer:
        writer.set_blocks(placements)
    return len(placements)
